cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/Users/akshatha_g/Documents/ntu-dsi-dcn-ntu-dsi-dcn-04d826f/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/Users/akshatha_g/Documents/ntu-dsi-dcn-ntu-dsi-dcn-04d826f/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Build.py", line 193, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 4324441232: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/local/gcc-6.2.0/bin/g++-6.2.0\', \'test.cpp.1.o\', \'-o\', \'/Users/akshatha_g/Documents/ntu-dsi-dcn-ntu-dsi-dcn-04d826f/build/.conf_check_fc0bab0b855f90bf0795892663948c43/testbuild/testprog\', \'-lrt\']\n'
